# -*- coding: utf-8 -*-
"""CustomTrackerFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124lpeltpTxJhhcZ87lQogbYAG53OSUch
"""

# ============================================================================
# CELL 1: Install Dependencies
# ============================================================================
"""
Run this cell first to install all required packages.
"""
print("✓ All dependencies installed successfully!")

# ============================================================================
# CELL 2: Imports and Device Setup
# ============================================================================

import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
from scipy.optimize import linear_sum_assignment
from collections import deque, OrderedDict
import os
from pathlib import Path
import gdown
from ultralytics import YOLO
import matplotlib.pyplot as plt
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

# Device setup
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# ============================================================================
# CELL 3: Custom Feature Extractor with Your Pretrained Model
# ============================================================================

class ImprovedBasicBlock(nn.Module):
    """Enhanced residual block with optional squeeze-excitation"""
    def __init__(self, c_in, c_out, stride=1, use_se=True, reduction=16):
        super(ImprovedBasicBlock, self).__init__()
        self.conv1 = nn.Conv2d(c_in, c_out, 3, stride, 1, bias=False)
        self.bn1 = nn.BatchNorm2d(c_out)
        self.conv2 = nn.Conv2d(c_out, c_out, 3, 1, 1, bias=False)
        self.bn2 = nn.BatchNorm2d(c_out)

        # Squeeze-and-Excitation block for channel attention
        self.use_se = use_se
        if use_se:
            self.se = nn.Sequential(
                nn.AdaptiveAvgPool2d(1),
                nn.Conv2d(c_out, c_out // reduction, 1),
                nn.ReLU(inplace=True),
                nn.Conv2d(c_out // reduction, c_out, 1),
                nn.Sigmoid()
            )

        # Skip connection handling
        self.downsample = nn.Sequential()
        if stride != 1 or c_in != c_out:
            self.downsample = nn.Sequential(
                nn.Conv2d(c_in, c_out, 1, stride, bias=False),
                nn.BatchNorm2d(c_out)
            )

    def forward(self, x):
        identity = self.downsample(x)
        out = F.relu(self.bn1(self.conv1(x)), inplace=True)
        out = self.bn2(self.conv2(out))
        if self.use_se:
            out = out * self.se(out)
        out += identity
        out = F.relu(out, inplace=True)
        return out


class GeM(nn.Module):
    """Generalized Mean Pooling"""
    def __init__(self, p=3.0, eps=1e-6):
        super(GeM, self).__init__()
        self.p = nn.Parameter(torch.ones(1) * p)
        self.eps = eps

    def forward(self, x):
        return F.adaptive_avg_pool2d(x.clamp(min=self.eps).pow(self.p), 1).pow(1.0 / self.p)


class ImprovedDeepSortWideResNet(nn.Module):
    """Your custom Deep SORT Re-ID model"""
    def __init__(self, num_features=128, num_classes=625, dropout=0.3,
                 use_se=True, use_gem=True):
        super(ImprovedDeepSortWideResNet, self).__init__()

        self.use_gem = use_gem

        # Efficient stem
        self.stem = nn.Sequential(
            nn.Conv2d(3, 32, 3, 1, 1, bias=False),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.Conv2d(32, 32, 3, 1, 1, bias=False),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True)
        )

        self.maxpool = nn.MaxPool2d(3, 2, 1)

        # Residual blocks
        self.layer1 = self._make_layer(32, 32, 2, stride=1, use_se=use_se)
        self.layer2 = self._make_layer(32, 64, 2, stride=2, use_se=use_se)
        self.layer3 = self._make_layer(64, 128, 2, stride=2, use_se=use_se)

        # Pooling
        if use_gem:
            self.global_pool = GeM()
        else:
            self.global_pool = nn.AdaptiveAvgPool2d(1)

        self.bn_neck = nn.BatchNorm1d(128)
        self.dropout = nn.Dropout(dropout) if dropout > 0 else nn.Identity()
        self.fc = nn.Linear(128, num_features)
        self.classifier = nn.Linear(num_features, num_classes, bias=False)

        self._init_weights()

    def _make_layer(self, c_in, c_out, num_blocks, stride, use_se):
        layers = []
        layers.append(ImprovedBasicBlock(c_in, c_out, stride, use_se))
        for _ in range(1, num_blocks):
            layers.append(ImprovedBasicBlock(c_out, c_out, 1, use_se))
        return nn.Sequential(*layers)

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, nn.BatchNorm2d) or isinstance(m, nn.BatchNorm1d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, 0, 0.01)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

    def forward(self, x, return_feature=False):
        x = self.stem(x)
        x = self.maxpool(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.global_pool(x)
        x = x.view(x.size(0), -1)
        x = self.bn_neck(x)
        x = self.dropout(x)
        features = self.fc(x)
        features = F.normalize(features, p=2, dim=1)

        if return_feature:
            return features

        logits = self.classifier(features)
        return logits


class FeatureExtractor:
    """Extract ReID features using your custom pretrained model."""
    def __init__(self, model_path='best_model.pth', device='cuda'):
        self.device = device

        print(f"Loading custom pretrained model from {model_path}...")

        # Build model architecture
        self.model = ImprovedDeepSortWideResNet(
            num_features=128,
            num_classes=625,
            dropout=0.3,
            use_se=True,
            use_gem=True
        ).to(device)

        # Load pretrained weights
        try:
            checkpoint = torch.load(model_path, map_location=device)

            # Handle different checkpoint formats
            if 'model_state_dict' in checkpoint:
                state_dict = checkpoint['model_state_dict']
            else:
                state_dict = checkpoint

            self.model.load_state_dict(state_dict)
            print(f"✓ Successfully loaded pretrained model from {model_path}")

            # Print checkpoint info if available
            if 'val_acc' in checkpoint:
                print(f"  Model validation accuracy: {checkpoint['val_acc']:.2f}%")
            if 'epoch' in checkpoint:
                print(f"  Trained for {checkpoint['epoch']} epochs")

        except FileNotFoundError:
            print(f"ERROR: Model file not found at {model_path}")
            print("Please ensure 'best_model.pth' is in the correct directory")
            raise
        except Exception as e:
            print(f"ERROR loading model: {e}")
            raise

        self.model.eval()

        # Image preprocessing (matches training)
        self.mean = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1).to(device)
        self.std = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1).to(device)
        self.size = (128, 64)  # height, width (matches training)

    def preprocess(self, img_crops):
        """Preprocess image crops for feature extraction."""
        if len(img_crops) == 0:
            return torch.empty(0, 3, *self.size).to(self.device)

        processed = []
        for crop in img_crops:
            # Resize to training size
            crop = cv2.resize(crop, (self.size[1], self.size[0]))
            # Convert to RGB and normalize
            crop = cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)
            crop = torch.from_numpy(crop).permute(2, 0, 1).float() / 255.0
            processed.append(crop)

        batch = torch.stack(processed).to(self.device)
        batch = (batch - self.mean) / self.std
        return batch

    @torch.no_grad()
    def extract(self, img, bboxes):
        """Extract features from bounding boxes in an image."""
        if len(bboxes) == 0:
            return np.empty((0, 128))  # 128-dim features

        crops = []
        for bbox in bboxes:
            x1, y1, x2, y2 = map(int, bbox)
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(img.shape[1], x2), min(img.shape[0], y2)
            crop = img[y1:y2, x1:x2]
            if crop.size > 0:
                crops.append(crop)
            else:
                crops.append(np.zeros((64, 64, 3), dtype=np.uint8))

        batch = self.preprocess(crops)
        features = self.model(batch, return_feature=True)
        return features.cpu().numpy()

# ============================================================================
# CELL 3.1: Verify Pretrained Model Availability
# ============================================================================

import os

def verify_model_file(model_path='best_model.pth'):
    """Check if the pretrained model exists and provide instructions if not."""

    if os.path.exists(model_path):
        # Get file size
        file_size = os.path.getsize(model_path) / (1024 * 1024)  # MB
        print(f"✓ Found pretrained model: {model_path}")
        print(f"  File size: {file_size:.2f} MB")
        return True
    else:
        print(f"❌ Pretrained model not found: {model_path}")
        print("\nPlease do ONE of the following:")
        print("\n1. Upload your best_model.pth file:")
        print("   - Click the folder icon on the left sidebar")
        print("   - Click the upload button")
        print("   - Select your best_model.pth file")
        print("\n2. Or update the path in CELL 9 if your file is in a different location")
        print("   Example: model_path='/content/checkpoints/best_model.pth'")
        return False

# Verify the model exists
verify_model_file('best_model.pth')

# ============================================================================
# CELL 3.2: Enhanced Feature Extractor with Appearance Buffer
# ============================================================================

class EnhancedFeatureExtractor(FeatureExtractor):
    """
    Enhanced feature extractor with:
    - Multi-scale feature extraction for low resolution
    - Appearance buffer for re-identification
    - Quality-aware feature extraction
    """

    def __init__(self, model_path='best_model.pth', device='cuda',
                 buffer_size=100, min_feature_quality=0.3):
        super().__init__(model_path, device)

        # Appearance buffer for re-ID
        self.appearance_buffer = []  # List of (feature, track_id, timestamp)
        self.buffer_size = buffer_size
        self.min_feature_quality = min_feature_quality

        # Multi-scale extraction for low-res robustness
        self.use_multiscale = True

    def assess_crop_quality(self, crop):
        """
        Assess if crop is good quality for feature extraction
        Returns quality score 0-1
        """
        if crop.size == 0:
            return 0.0

        h, w = crop.shape[:2]

        # Check minimum size
        if h < 40 or w < 20:
            return 0.1

        # Check aspect ratio (person should be ~2:1)
        aspect = h / (w + 1e-6)
        aspect_score = 1.0 - abs(aspect - 2.0) / 2.0
        aspect_score = max(0, min(1, aspect_score))

        # Check blurriness using Laplacian variance
        gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
        laplacian_var = cv2.Laplacian(gray, cv2.CV_64F).var()
        blur_score = min(1.0, laplacian_var / 100.0)

        # Check brightness
        mean_brightness = np.mean(gray)
        brightness_score = 1.0 - abs(mean_brightness - 128) / 128

        # Combined quality score
        quality = (aspect_score * 0.4 + blur_score * 0.4 + brightness_score * 0.2)

        return quality

    def extract_multiscale(self, crop):
        """Extract features at multiple scales for robustness"""
        features_list = []

        # Original scale
        crop_resized = cv2.resize(crop, (self.size[1], self.size[0]))
        crop_rgb = cv2.cvtColor(crop_resized, cv2.COLOR_BGR2RGB)
        crop_tensor = torch.from_numpy(crop_rgb).permute(2, 0, 1).float() / 255.0
        crop_tensor = (crop_tensor.unsqueeze(0).to(self.device) - self.mean) / self.std

        with torch.no_grad():
            feat = self.model(crop_tensor, return_feature=True)
            features_list.append(feat)

        # If using multiscale and crop is low quality, add augmented versions
        quality = self.assess_crop_quality(crop)

        if quality < 0.6 and self.use_multiscale:
            # Slightly zoomed in (focuses on torso)
            h, w = crop.shape[:2]
            crop_zoom = crop[int(h*0.1):int(h*0.9), int(w*0.1):int(w*0.9)]
            if crop_zoom.size > 0:
                crop_zoom_resized = cv2.resize(crop_zoom, (self.size[1], self.size[0]))
                crop_zoom_rgb = cv2.cvtColor(crop_zoom_resized, cv2.COLOR_BGR2RGB)
                crop_zoom_tensor = torch.from_numpy(crop_zoom_rgb).permute(2, 0, 1).float() / 255.0
                crop_zoom_tensor = (crop_zoom_tensor.unsqueeze(0).to(self.device) - self.mean) / self.std

                with torch.no_grad():
                    feat_zoom = self.model(crop_zoom_tensor, return_feature=True)
                    features_list.append(feat_zoom)

        # Average features from multiple scales
        features = torch.mean(torch.stack(features_list), dim=0)
        return features

    @torch.no_grad()
    def extract(self, img, bboxes, return_quality=False):
        """Extract features with quality assessment"""
        if len(bboxes) == 0:
            return np.empty((0, 128))

        crops = []
        qualities = []

        for bbox in bboxes:
            x1, y1, x2, y2 = map(int, bbox)
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(img.shape[1], x2), min(img.shape[0], y2)
            crop = img[y1:y2, x1:x2]

            if crop.size > 0:
                crops.append(crop)
                quality = self.assess_crop_quality(crop)
                qualities.append(quality)
            else:
                crops.append(np.zeros((64, 64, 3), dtype=np.uint8))
                qualities.append(0.0)

        # Extract features
        features_list = []
        for crop, quality in zip(crops, qualities):
            if quality > self.min_feature_quality:
                feat = self.extract_multiscale(crop)
            else:
                # For very low quality, use standard extraction
                batch = self.preprocess([crop])
                feat = self.model(batch, return_feature=True)

            features_list.append(feat)

        features = torch.cat(features_list, dim=0).cpu().numpy()

        if return_quality:
            return features, qualities
        return features

    def add_to_buffer(self, feature, track_id, timestamp):
        """Add feature to appearance buffer for re-ID"""
        self.appearance_buffer.append({
            'feature': feature,
            'track_id': track_id,
            'timestamp': timestamp
        })

        # Keep buffer size limited
        if len(self.appearance_buffer) > self.buffer_size:
            self.appearance_buffer.pop(0)

    def search_buffer(self, feature, max_age=120, threshold=0.5):
        """Search buffer for matching track"""
        if len(self.appearance_buffer) == 0:
            return None

        best_match = None
        best_similarity = threshold

        for entry in reversed(self.appearance_buffer):
            # Skip if too old
            if entry['timestamp'] < (len(self.appearance_buffer) - max_age):
                continue

            # Calculate similarity
            feature = feature / (np.linalg.norm(feature) + 1e-6)
            stored = entry['feature'] / (np.linalg.norm(entry['feature']) + 1e-6)
            similarity = np.dot(feature, stored)

            if similarity > best_similarity:
                best_similarity = similarity
                best_match = entry['track_id']

        return best_match

# ============================================================================
# CELL 4: NSA Kalman Filter (Robust to Occlusion & Noise)
# ============================================================================

class NSAKalmanFilter:
    """
    Noise Scale Adaptive (NSA) Kalman Filter.
    Adapts measurement noise (R) based on detection confidence.
    """
    def __init__(self):
        # State: [x, y, w, h, vx, vy, vw, vh]
        self.dt = 1.0

        # 1. Motion Model (Constant Velocity)
        self.F = np.eye(8)
        for i in range(4):
            self.F[i, i+4] = self.dt

        # 2. Measurement Matrix
        self.H = np.eye(4, 8)

        # 3. Standard Measurement Noise (R)
        # We use a base R, but it will be scaled dynamically
        self.std_weight_position = 1.0 / 20
        self.std_weight_velocity = 1.0 / 160

        # 4. Process Noise (Q) - Tuned for smoother tracking during occlusion
        self.Q = np.eye(8)
        # Position noise (allow some jitter)
        self.Q[0:4, 0:4] *= 0.05
        # Velocity noise (assume velocity changes slowly)
        self.Q[4:8, 4:8] *= 0.00625

        # 5. Covariance (P)
        self.P = np.eye(8) * 10

        # State vector
        self.x = np.zeros(8)

    def init(self, measurement):
        """Initialize with [x, y, w, h]"""
        self.x[:4] = measurement
        self.x[4:] = 0

        # Heuristic: Set initial velocity covariance high (we don't know velocity yet)
        self.P[4:, 4:] *= 1000

    def predict(self):
        """
        Predict next state.
        During occlusion, P naturally grows, increasing uncertainty.
        """
        self.x = self.F @ self.x
        self.P = self.F @ self.P @ self.F.T + self.Q
        return self.x[:4]

    def update(self, measurement, confidence=1.0):
        """
        NSA Update: Scales noise R based on detection confidence.

        Args:
            measurement: [x, y, w, h]
            confidence: detection confidence (0.0 to 1.0)
        """
        # 1. Dynamic R Calculation (The NSA Trick)
        # Low confidence -> High R -> Trust Prediction (Handles occlusion/blur)
        # High confidence -> Low R -> Trust Measurement

        # Base noise based on box size (height)
        h = max(measurement[3], 10) # Avoid division by zero
        std_pos = self.std_weight_position * h
        std_vel = self.std_weight_velocity * h

        # Scale factor: If confidence is low (e.g., 0.5), we increase noise
        # Formula: (1 - confidence) * factor.
        # We add a small epsilon to prevent R from being 0.
        inv_conf = 1.0 - confidence
        scale = 1.0 + (inv_conf * 10.0) # Intense scaling for low confidence

        # Construct Adaptive R
        R = np.eye(4)
        R[0, 0] = std_pos ** 2 * scale  # x
        R[1, 1] = std_pos ** 2 * scale  # y
        R[2, 2] = std_pos ** 2 * scale  # w
        R[3, 3] = std_pos ** 2 * scale  # h

        # 2. Standard Kalman Update with Adaptive R
        y = measurement - self.H @ self.x
        S = self.H @ self.P @ self.H.T + R
        K = self.P @ self.H.T @ np.linalg.inv(S)

        self.x = self.x + K @ y
        I = np.eye(8)
        self.P = (I - K @ self.H) @ self.P

        return self.x[:4]

    def get_state(self):
        return self.x[:4]

# ============================================================================
# CELL 5: Global Motion Compensation (GMC)
# ============================================================================

class GMC:
    """
    Global Motion Compensation using ORB features and affine transformation.
    Compensates for camera motion to improve Kalman filter predictions.
    """
    def __init__(self, method='orb', downscale=2):
        self.method = method
        self.downscale = downscale
        self.prevFrame = None
        self.prevKeypoints = None
        self.prevDescriptors = None
        self.initializedFirstFrame = False

        # ORB detector
        self.detector = cv2.ORB_create(nfeatures=1000)
        self.matcher = cv2.BFMatcher(cv2.NORM_HAMMING)

    def apply(self, frame, detections=None):
        """
        Estimate camera motion between frames.
        Returns: 2x3 affine transformation matrix (or eye matrix if failed)
        """
        H, W = frame.shape[:2]
        H_ds, W_ds = H // self.downscale, W // self.downscale

        # Downscale frame for efficiency
        frame_ds = cv2.resize(frame, (W_ds, H_ds))
        frame_gray = cv2.cvtColor(frame_ds, cv2.COLOR_BGR2GRAY)

        if not self.initializedFirstFrame:
            self.prevFrame = frame_gray
            self.prevKeypoints, self.prevDescriptors = self.detector.detectAndCompute(frame_gray, None)
            self.initializedFirstFrame = True
            return np.eye(2, 3)

        # Detect features in current frame
        keypoints, descriptors = self.detector.detectAndCompute(frame_gray, None)

        if descriptors is None or self.prevDescriptors is None:
            self.prevFrame = frame_gray
            self.prevKeypoints = keypoints
            self.prevDescriptors = descriptors
            return np.eye(2, 3)

        # Match features
        matches = self.matcher.knnMatch(self.prevDescriptors, descriptors, k=2)

        # Apply ratio test
        good_matches = []
        for match_pair in matches:
            if len(match_pair) == 2:
                m, n = match_pair
                if m.distance < 0.75 * n.distance:
                    good_matches.append(m)

        if len(good_matches) < 10:
            self.prevFrame = frame_gray
            self.prevKeypoints = keypoints
            self.prevDescriptors = descriptors
            return np.eye(2, 3)

        # Extract matched keypoints
        prevPts = np.float32([self.prevKeypoints[m.queryIdx].pt for m in good_matches])
        currPts = np.float32([keypoints[m.trainIdx].pt for m in good_matches])

        # Estimate affine transformation
        transform, inliers = cv2.estimateAffinePartial2D(prevPts, currPts, method=cv2.RANSAC)

        if transform is None:
            transform = np.eye(2, 3)
        else:
            # Scale transform back to original resolution
            transform[:, 2] *= self.downscale

        # Update previous frame
        self.prevFrame = frame_gray
        self.prevKeypoints = keypoints
        self.prevDescriptors = descriptors

        return transform

# ============================================================================
# CELL 6: BoT-SORT Tracker Class
# ============================================================================

class Track:
    """Individual track with NSA Kalman filter and appearance features."""
    _count = 0

    def __init__(self, bbox, feature, track_id=None):
        """
        Args:
            bbox: [x1, y1, x2, y2]
            feature: appearance feature vector
        """
        self.track_id = Track._count if track_id is None else track_id
        Track._count += 1

        # Convert bbox to [cx, cy, w, h]
        x1, y1, x2, y2 = bbox
        cx = (x1 + x2) / 2
        cy = (y1 + y2) / 2
        w = x2 - x1
        h = y2 - y1

        # Initialize NSA Kalman filter
        # NOTE: Ensure NSAKalmanFilter class (Cell 4) is defined before running this!
        self.kf = NSAKalmanFilter()
        self.kf.init(np.array([cx, cy, w, h]))

        # Appearance features (keep a gallery of recent features)
        self.features = deque([feature], maxlen=30)

        # Track state
        self.hits = 1
        self.age = 1
        self.time_since_update = 0
        self.state = 'tentative'  # tentative, confirmed, deleted

        # Trajectory for visualization
        self.trajectory = deque(maxlen=30)
        self.trajectory.append((cx, cy))

    def predict(self):
        """Predict next position using Kalman filter."""
        self.age += 1
        self.time_since_update += 1
        pred = self.kf.predict()
        return self._xywh_to_xyxy(pred)

    def update(self, bbox, feature, confidence=1.0):
        """
        Update track with new detection.
        Args:
            bbox: [x1, y1, x2, y2]
            feature: appearance feature
            confidence: detection confidence score (for NSA Kalman Filter)
        """
        x1, y1, x2, y2 = bbox
        cx = (x1 + x2) / 2
        cy = (y1 + y2) / 2
        w = x2 - x1
        h = y2 - y1

        # NSA Update: Pass confidence to the Kalman Filter
        self.kf.update(np.array([cx, cy, w, h]), confidence=confidence)

        self.features.append(feature)
        self.trajectory.append((cx, cy))

        self.hits += 1
        self.time_since_update = 0

        if self.state == 'tentative' and self.hits >= 3:
            self.state = 'confirmed'

    def mark_missed(self):
        """Mark track as missed."""
        if self.state == 'tentative':
            self.state = 'deleted'
        elif self.time_since_update > 30:
            self.state = 'deleted'

    def get_state(self):
        """Get current bbox [x1, y1, x2, y2]."""
        xywh = self.kf.get_state()
        return self._xywh_to_xyxy(xywh)

    def get_feature(self):
        """Get averaged appearance feature."""
        return np.mean(self.features, axis=0)

    @staticmethod
    def _xywh_to_xyxy(xywh):
        """Convert [cx, cy, w, h] to [x1, y1, x2, y2]."""
        cx, cy, w, h = xywh
        x1 = cx - w / 2
        y1 = cy - h / 2
        x2 = cx + w / 2
        y2 = cy + h / 2
        return np.array([x1, y1, x2, y2])


class BoTSORT:
    """BoT-SORT tracker with GMC and fused matching."""
    def __init__(self, feature_extractor, max_age=120, min_hits=4,
                 iou_threshold=0.3, lambda_iou=0.98, lambda_reid=0.02):
        """
        Args:
            feature_extractor: FeatureExtractor instance
            max_age: maximum frames to keep alive a track without updates
            min_hits: minimum hits before confirming a track
            iou_threshold: IoU threshold for matching
            lambda_iou: weight for IoU distance in fused cost
            lambda_reid: weight for ReID distance in fused cost
        """
        self.feature_extractor = feature_extractor
        self.max_age = max_age
        self.min_hits = min_hits
        self.iou_threshold = iou_threshold
        self.lambda_iou = lambda_iou
        self.lambda_reid = lambda_reid

        self.tracks = []
        self.frame_count = 0

        # GMC for camera motion compensation
        self.gmc = GMC(method='orb', downscale=2)

    def update(self, frame, detections):
        """
        Update tracker with new detections.
        Args:
            frame: current frame (H, W, 3)
            detections: Nx5 array [x1, y1, x2, y2, conf]
        Returns:
            list of active tracks with [x1, y1, x2, y2, track_id]
        """
        self.frame_count += 1

        # Apply GMC to compensate for camera motion
        transform = self.gmc.apply(frame, detections)
        self._camera_update(transform)

        # Predict all tracks
        for track in self.tracks:
            track.predict()

        # Extract features for detections
        if len(detections) > 0:
            bboxes = detections[:, :4]
            features = self.feature_extractor.extract(frame, bboxes)
            # Extract confidences if available, else default to 1.0
            confidences = detections[:, 4] if detections.shape[1] > 4 else np.ones(len(detections))
        else:
            bboxes = np.empty((0, 4))
            features = np.empty((0, 512))
            confidences = np.empty(0)

        # Match detections to tracks
        matches, unmatched_dets, unmatched_tracks = self._match(
            detections, features
        )

        # Update matched tracks
        for track_idx, det_idx in matches:
            # Pass detection confidence to update method
            self.tracks[track_idx].update(
                bboxes[det_idx],
                features[det_idx],
                confidence=confidences[det_idx]
            )

        # Mark unmatched tracks as missed
        for track_idx in unmatched_tracks:
            self.tracks[track_idx].mark_missed()

        # Create new tracks for unmatched detections
        for det_idx in unmatched_dets:
            new_track = Track(bboxes[det_idx], features[det_idx])
            # Initial update to set confidence
            new_track.update(bboxes[det_idx], features[det_idx], confidence=confidences[det_idx])
            self.tracks.append(new_track)

        # Remove deleted tracks
        self.tracks = [t for t in self.tracks if t.state != 'deleted']

        # Return confirmed tracks
        outputs = []
        for track in self.tracks:
            if track.state == 'confirmed':
                bbox = track.get_state()
                outputs.append([*bbox, track.track_id])

        return np.array(outputs) if outputs else np.empty((0, 5))

    def _camera_update(self, transform):
        """Apply camera motion compensation to all tracks."""
        for track in self.tracks:
            # Get current state
            cx, cy, w, h = track.kf.x[:4]

            # Apply affine transformation to center point
            pt = np.array([[cx, cy]], dtype=np.float32)
            pt_transformed = cv2.transform(pt.reshape(1, 1, 2), transform).reshape(2)

            # Update Kalman filter state
            track.kf.x[0] = pt_transformed[0]
            track.kf.x[1] = pt_transformed[1]

    def _match(self, detections, det_features):
        """Match detections to tracks using fused IoU + ReID cost."""
        if len(self.tracks) == 0 or len(detections) == 0:
            return [], list(range(len(detections))), []

        # Get track predictions and features
        track_bboxes = np.array([t.get_state() for t in self.tracks])
        track_features = np.array([t.get_feature() for t in self.tracks])

        det_bboxes = detections[:, :4]

        # Compute IoU distance matrix
        iou_dist = self._iou_distance(track_bboxes, det_bboxes)

        # Compute cosine distance matrix for ReID
        cosine_dist = self._cosine_distance(track_features, det_features)

        # Fused cost matrix
        cost_matrix = self.lambda_iou * iou_dist + self.lambda_reid * cosine_dist

        # Hungarian algorithm for assignment
        row_ind, col_ind = linear_sum_assignment(cost_matrix)

        matches = []
        unmatched_tracks = list(range(len(self.tracks)))
        unmatched_dets = list(range(len(detections)))

        for r, c in zip(row_ind, col_ind):
            if cost_matrix[r, c] < 0.7:  # threshold for valid match
                matches.append((r, c))
                unmatched_tracks.remove(r)
                unmatched_dets.remove(c)

        return matches, unmatched_dets, unmatched_tracks

    @staticmethod
    def _iou_distance(bboxes1, bboxes2):
        """Compute IoU distance matrix."""
        n = len(bboxes1)
        m = len(bboxes2)

        if n == 0 or m == 0:
            return np.zeros((n, m))

        # Expand dimensions for broadcasting
        b1 = np.expand_dims(bboxes1, 1)  # (n, 1, 4)
        b2 = np.expand_dims(bboxes2, 0)  # (1, m, 4)

        # Intersection
        x1 = np.maximum(b1[..., 0], b2[..., 0])
        y1 = np.maximum(b1[..., 1], b2[..., 1])
        x2 = np.minimum(b1[..., 2], b2[..., 2])
        y2 = np.minimum(b1[..., 3], b2[..., 3])

        inter_area = np.maximum(0, x2 - x1) * np.maximum(0, y2 - y1)

        # Union
        b1_area = (b1[..., 2] - b1[..., 0]) * (b1[..., 3] - b1[..., 1])
        b2_area = (b2[..., 2] - b2[..., 0]) * (b2[..., 3] - b2[..., 1])
        union_area = b1_area + b2_area - inter_area

        iou = inter_area / (union_area + 1e-6)
        return 1 - iou

    @staticmethod
    def _cosine_distance(features1, features2):
        """Compute cosine distance matrix."""
        # Normalize features
        features1 = features1 / (np.linalg.norm(features1, axis=1, keepdims=True) + 1e-6)
        features2 = features2 / (np.linalg.norm(features2, axis=1, keepdims=True) + 1e-6)

        # Cosine similarity
        similarity = np.dot(features1, features2.T)

        # Convert to distance
        return 1 - similarity

# ============================================================================
# CELL 6.1: Enhanced Track Class with Confidence and Quality
# ============================================================================

class EnhancedTrack(Track):
    """Enhanced track with confidence scoring and better occlusion handling"""

    def __init__(self, bbox, feature, track_id=None, quality=1.0):
        # Initialize parent
        super().__init__(bbox, feature, track_id)

        # Confidence tracking
        self.detection_confidence = 1.0
        self.feature_quality = quality
        self.consecutive_misses = 0

        # Occlusion handling
        self.is_occluded = False
        self.occlusion_frames = 0

        # Re-ID support
        self.last_seen_frame = 0
        self.total_detections = 1

        # Ensure we are using NSA Kalman Filter (double check)
        # Typically initialized in parent, but we want to be sure
        if not isinstance(self.kf, NSAKalmanFilter):
            self.kf = NSAKalmanFilter()
            # Re-init state
            x1, y1, x2, y2 = bbox
            cx, cy = (x1 + x2) / 2, (y1 + y2) / 2
            w, h = x2 - x1, y2 - y1
            self.kf.init(np.array([cx, cy, w, h]))

    def predict(self):
        """Predict with confidence decay and velocity momentum"""
        self.age += 1
        self.time_since_update += 1
        self.consecutive_misses += 1

        # Decay confidence when missing
        self.detection_confidence *= 0.95

        # Check if occluded (missing but high confidence before)
        if self.consecutive_misses > 3 and self.detection_confidence > 0.5:
            self.is_occluded = True
            self.occlusion_frames += 1

        # MOMENTUM LOGIC: If track is lost for > 5 frames, decay velocity
        # This prevents it from floating away if it was moving fast when lost
        if self.time_since_update > 5:
            self.kf.x[4:] *= 0.9

        pred = self.kf.predict()
        return self._xywh_to_xyxy(pred)

    def update(self, bbox, feature, quality=1.0):
        """Update with quality-weighted feature and NSA logic"""
        # 1. Update internal confidence/metrics first

        # Reset counters
        self.consecutive_misses = 0
        self.is_occluded = False
        self.occlusion_frames = 0

        # Update confidence based on quality
        self.detection_confidence = min(1.0, self.detection_confidence + 0.1)
        self.feature_quality = quality
        self.total_detections += 1

        # 2. Call Parent Update (but pass the confidence!)
        # We perform the super().update logic manually here to control the arguments
        # specifically for NSAKalmanFilter

        x1, y1, x2, y2 = bbox
        cx = (x1 + x2) / 2
        cy = (y1 + y2) / 2
        w = x2 - x1
        h = y2 - y1

        # CRITICAL: Pass detection_confidence to NSA Kalman Filter
        # High confidence = tight covariance (trust measurement)
        # Low confidence = loose covariance (trust prediction)
        self.kf.update(np.array([cx, cy, w, h]), confidence=self.detection_confidence)

        self.features.append(feature)
        self.trajectory.append((cx, cy))

        self.hits += 1
        self.time_since_update = 0

        if self.state == 'tentative' and self.hits >= 3:
            self.state = 'confirmed'

    def mark_missed(self):
        """Enhanced missed marking with confidence decay"""
        self.consecutive_misses += 1
        self.detection_confidence *= 0.9

        # More lenient deletion for high-confidence tracks
        if self.state == 'tentative':
            self.state = 'deleted'
        elif self.detection_confidence < 0.2:
            self.state = 'deleted'
        elif self.time_since_update > 30:
            self.state = 'deleted'
        # Give more time to occluded tracks
        elif self.is_occluded and self.time_since_update > 15:
            self.state = 'deleted'

    def get_confidence(self):
        """Get overall track confidence"""
        # Combine detection confidence with track maturity
        maturity_score = min(1.0, self.total_detections / 10.0)
        return self.detection_confidence * 0.7 + maturity_score * 0.3

# ============================================================================
# CELL 6.2: Enhanced BoT-SORT with Re-identification Buffer
# ============================================================================

class EnhancedBoTSORT(BoTSORT):
    """
    Enhanced BoT-SORT with:
    - Re-identification buffer for re-entering persons
    - Better occlusion handling
    - Confidence-based track management
    """

    def __init__(self, feature_extractor, max_age=120, min_hits=3,
                 iou_threshold=0.3, lambda_iou=0.98, lambda_reid=0.02,
                 reid_threshold=0.8, reid_buffer_size=50):

        # Initialize parent class but we'll override some methods
        self.feature_extractor = feature_extractor
        self.max_age = max_age
        self.min_hits = min_hits
        self.iou_threshold = iou_threshold
        self.lambda_iou = lambda_iou
        self.lambda_reid = lambda_reid

        self.tracks = []
        self.frame_count = 0

        # GMC for camera motion compensation
        self.gmc = GMC(method='orb', downscale=2)

        # Re-ID buffer settings
        self.reid_threshold = reid_threshold
        self.reid_buffer_size = reid_buffer_size
        self.lost_tracks = []  # Tracks that were lost but might return

    def update(self, frame, detections):
        """Enhanced update with re-identification"""
        self.frame_count += 1

        # Apply GMC
        transform = self.gmc.apply(frame, detections)
        self._camera_update(transform)

        # Predict all tracks
        for track in self.tracks:
            track.predict()

        # Extract features with quality
        if len(detections) > 0:
            bboxes = detections[:, :4]
            features, qualities = self.feature_extractor.extract(
                frame, bboxes, return_quality=True
            )
        else:
            bboxes = np.empty((0, 4))
            features = np.empty((0, 128))
            qualities = []

        # First matching: active tracks
        matches, unmatched_dets, unmatched_tracks = self._match(
            detections, features, qualities
        )

        # Update matched tracks
        for track_idx, det_idx in matches:
            self.tracks[track_idx].update(
                bboxes[det_idx], features[det_idx], qualities[det_idx]
            )
            self.tracks[track_idx].last_seen_frame = self.frame_count

        # Second matching: Try to re-identify from lost tracks
        if len(unmatched_dets) > 0 and len(self.lost_tracks) > 0:
            reid_matches = self._reid_match(
                unmatched_dets, bboxes, features, qualities
            )

            for lost_idx, det_idx in reid_matches:
                # Recover lost track
                recovered_track = self.lost_tracks.pop(lost_idx)
                recovered_track.update(
                    bboxes[det_idx], features[det_idx], qualities[det_idx]
                )
                recovered_track.state = 'confirmed'
                recovered_track.time_since_update = 0
                self.tracks.append(recovered_track)

                # Remove from unmatched
                unmatched_dets = [d for d in unmatched_dets if d != det_idx]

        # Mark unmatched tracks as missed
        for track_idx in unmatched_tracks:
            self.tracks[track_idx].mark_missed()

        # Create new tracks for remaining unmatched detections
        for det_idx in unmatched_dets:
            quality = qualities[det_idx] if det_idx < len(qualities) else 0.5
            # Only create track if quality is reasonable
            if quality > 0.3:
                new_track = EnhancedTrack(
                    bboxes[det_idx], features[det_idx], quality=quality
                )
                new_track.last_seen_frame = self.frame_count
                self.tracks.append(new_track)

        # Manage track lifecycle
        self._manage_tracks()

        # Return confirmed tracks with minimum confidence
        outputs = []
        for track in self.tracks:
            if track.state == 'confirmed' and track.get_confidence() > 0.3:
                bbox = track.get_state()
                outputs.append([*bbox, track.track_id])

        return np.array(outputs) if outputs else np.empty((0, 5))

    def _reid_match(self, unmatched_dets, bboxes, features, qualities):
        """Match unmatched detections with lost tracks using Re-ID"""
        if len(self.lost_tracks) == 0:
            return []

        # Get features of lost tracks
        lost_features = np.array([t.get_feature() for t in self.lost_tracks])

        # Get features of unmatched detections
        unmatched_features = features[unmatched_dets]

        # Calculate similarity matrix
        similarity = np.dot(unmatched_features, lost_features.T)

        # Apply threshold
        similarity[similarity < self.reid_threshold] = 0

        # Hungarian matching
        from scipy.optimize import linear_sum_assignment
        cost = 1 - similarity
        row_ind, col_ind = linear_sum_assignment(cost)

        matches = []
        for r, c in zip(row_ind, col_ind):
            if similarity[r, c] > self.reid_threshold:
                matches.append((c, unmatched_dets[r]))

        return matches

    def _manage_tracks(self):
        """Manage track lifecycle with lost track buffer"""
        active_tracks = []

        for track in self.tracks:
            if track.state == 'deleted':
                # Move to lost tracks if it was a good track
                if (track.total_detections > 5 and
                    track.get_confidence() > 0.4 and
                    len(self.lost_tracks) < self.reid_buffer_size):
                    self.lost_tracks.append(track)
            else:
                active_tracks.append(track)

        self.tracks = active_tracks

        # Clean old lost tracks
        current_frame = self.frame_count
        self.lost_tracks = [
            t for t in self.lost_tracks
            if (current_frame - t.last_seen_frame) < 60  # Keep for 60 frames
        ]

    def _match(self, detections, det_features, qualities):
        """Enhanced matching with quality weighting"""
        if len(self.tracks) == 0 or len(detections) == 0:
            return [], list(range(len(detections))), []

        # Filter tracks by confidence
        valid_tracks = [
            i for i, t in enumerate(self.tracks)
            if t.get_confidence() > 0.2
        ]

        if len(valid_tracks) == 0:
            return [], list(range(len(detections))), []

        # Get track predictions and features
        track_bboxes = np.array([self.tracks[i].get_state() for i in valid_tracks])
        track_features = np.array([self.tracks[i].get_feature() for i in valid_tracks])

        det_bboxes = detections[:, :4]

        # Compute IoU distance
        iou_dist = self._iou_distance(track_bboxes, det_bboxes)

        # Compute cosine distance
        cosine_dist = self._cosine_distance(track_features, det_features)

        # Weight by quality
        quality_weights = np.array(qualities).reshape(-1, 1)
        quality_weights = np.clip(quality_weights, 0.3, 1.0)

        # Fused cost with quality weighting
        cost_matrix = (
            self.lambda_iou * iou_dist +
            self.lambda_reid * cosine_dist * quality_weights.T
        )

        # Hungarian algorithm
        from scipy.optimize import linear_sum_assignment
        row_ind, col_ind = linear_sum_assignment(cost_matrix)

        matches = []
        unmatched_tracks = list(range(len(valid_tracks)))
        unmatched_dets = list(range(len(detections)))

        for r, c in zip(row_ind, col_ind):
            if cost_matrix[r, c] < 0.7:
                matches.append((valid_tracks[r], c))
                if r in unmatched_tracks:
                    unmatched_tracks.remove(r)
                if c in unmatched_dets:
                    unmatched_dets.remove(c)

        # Map back to original track indices
        unmatched_tracks = [valid_tracks[i] for i in unmatched_tracks]

        return matches, unmatched_dets, unmatched_tracks

# ============================================================================
# CELL 6.3: Long-Term Memory Manager for Persistent Re-identification
# ============================================================================

class LongTermMemory:
    """
    Long-term memory for storing identity embeddings across the entire video.
    Prevents assigning new IDs to previously seen persons.
    """

    def __init__(self, max_identities=200, similarity_threshold=0.50,
                 features_per_id=128, quality_threshold=0.4):
        """
        Args:
            max_identities: Maximum number of identities to remember
            similarity_threshold: Threshold for matching against memory
            features_per_id: Number of features to store per identity
            quality_threshold: Minimum quality to store features in memory
        """
        self.memory = {}  # {track_id: {'features': [], 'last_seen': frame, 'total_appearances': int}}
        self.max_identities = max_identities
        self.similarity_threshold = similarity_threshold
        self.features_per_id = features_per_id
        self.quality_threshold = quality_threshold

    def add_identity(self, track_id, feature, frame_num, quality=1.0):
        """Add or update an identity in memory"""
        # Only store high-quality features
        if quality < self.quality_threshold:
            return

        if track_id not in self.memory:
            self.memory[track_id] = {
                'features': deque([feature], maxlen=self.features_per_id),
                'last_seen': frame_num,
                'total_appearances': 1,
                'first_seen': frame_num
            }
        else:
            self.memory[track_id]['features'].append(feature)
            self.memory[track_id]['last_seen'] = frame_num
            self.memory[track_id]['total_appearances'] += 1

    def search_memory(self, feature, current_frame, max_frames_gap=300):
        """
        Search memory for matching identity

        Args:
            feature: Query feature vector
            current_frame: Current frame number
            max_frames_gap: Maximum gap in frames to consider a match

        Returns:
            matched_track_id or None
        """
        if len(self.memory) == 0:
            return None

        best_match_id = None
        best_similarity = self.similarity_threshold

        for track_id, data in self.memory.items():
            # Skip if identity was seen too long ago (optional filtering)
            # Commenting this out allows matching across entire video duration
            # if (current_frame - data['last_seen']) > max_frames_gap:
            #     continue

            # Calculate average similarity with stored features
            stored_features = np.array(list(data['features']))
            similarities = np.dot(stored_features, feature)
            avg_similarity = np.mean(similarities)
            max_similarity = np.max(similarities)

            # Use weighted score: favor both high average and high max
            combined_score = 0.6 * avg_similarity + 0.4 * max_similarity

            if combined_score > best_similarity:
                best_similarity = combined_score
                best_match_id = track_id

        if best_match_id is not None:
            print(f"  🔍 Memory Match! Recovered ID {best_match_id} (similarity: {best_similarity:.3f})")

        return best_match_id

    def get_identity_stats(self, track_id):
        """Get statistics about an identity"""
        if track_id in self.memory:
            return self.memory[track_id]
        return None

    def cleanup_memory(self, current_frame, max_age=1000):
        """Remove very old identities to prevent memory overflow"""
        if len(self.memory) > self.max_identities:
            # Remove oldest identities that haven't been seen recently
            sorted_ids = sorted(
                self.memory.items(),
                key=lambda x: (x[1]['last_seen'], x[1]['total_appearances'])
            )

            # Keep most recent and most frequently seen
            ids_to_remove = [id for id, _ in sorted_ids[:len(self.memory) - self.max_identities]]

            for id in ids_to_remove:
                del self.memory[id]
                print(f"  🗑️ Removed old identity {id} from memory")

    def get_memory_summary(self):
        """Get summary of memory state"""
        if len(self.memory) == 0:
            return "Memory: Empty"

        total_identities = len(self.memory)
        total_features = sum(len(data['features']) for data in self.memory.values())
        avg_appearances = np.mean([data['total_appearances'] for data in self.memory.values()])

        return f"Memory: {total_identities} IDs, {total_features} features, avg {avg_appearances:.1f} appearances"

# ============================================================================
# CELL 6.4: Memory-Aware Enhanced Track
# ============================================================================

class MemoryAwareTrack(EnhancedTrack):
    """Track that integrates with long-term memory"""

    def __init__(self, bbox, feature, track_id=None, quality=1.0, from_memory=False):
        super().__init__(bbox, feature, track_id, quality)

        # Memory tracking
        self.from_memory = from_memory  # Was this track recovered from memory?
        self.memory_confirmed = False  # Has this track been confirmed via memory?

        # Store features for memory
        self.high_quality_features = []  # Store only high-quality features

    def update(self, bbox, feature, quality=1.0):
        """Update track and store high-quality features"""
        super().update(bbox, feature, quality)

        # Store high-quality features for memory
        if quality > 0.5:
            self.high_quality_features.append(feature)
            # Keep only recent high-quality features
            if len(self.high_quality_features) > 10:
                self.high_quality_features.pop(0)

    def get_memory_feature(self):
        """Get best feature for storing in memory"""
        if len(self.high_quality_features) > 0:
            # Return average of high-quality features
            return np.mean(self.high_quality_features, axis=0)
        else:
            return self.get_feature()

# ============================================================================
# CELL 6.5: Ultimate BoT-SORT with Long-Term Memory
# ============================================================================

class MemoryEnhancedBoTSORT(EnhancedBoTSORT):
    """
    Ultimate BoT-SORT with:
    - Long-term memory for entire video
    - Multi-stage matching: active tracks → lost tracks → memory
    - Prevents ID re-assignment for previously seen persons
    """

    def __init__(self, feature_extractor, max_age=120, min_hits=3,
                 iou_threshold=0.3, lambda_iou=0.95, lambda_reid=0.05,
                 reid_threshold=0.70, reid_buffer_size=50,
                 memory_threshold=0.5, memory_size=200):

        super().__init__(
            feature_extractor, max_age, min_hits, iou_threshold,
            lambda_iou, lambda_reid, reid_threshold, reid_buffer_size
        )

        # Long-term memory
        self.long_term_memory = LongTermMemory(
            max_identities=memory_size,
            similarity_threshold=memory_threshold,
            features_per_id=10,
            quality_threshold=0.4
        )

        # Statistics
        self.stats = {
            'memory_recoveries': 0,
            'reid_buffer_recoveries': 0,
            'new_ids_created': 0
        }

    def update(self, frame, detections):
        """Enhanced update with three-stage matching"""
        self.frame_count += 1

        # Apply GMC
        transform = self.gmc.apply(frame, detections)
        self._camera_update(transform)

        # Predict all tracks
        for track in self.tracks:
            track.predict()

        # Extract features with quality
        if len(detections) > 0:
            bboxes = detections[:, :4]
            features, qualities = self.feature_extractor.extract(
                frame, bboxes, return_quality=True
            )
        else:
            bboxes = np.empty((0, 4))
            features = np.empty((0, 128))
            qualities = []

        # === STAGE 1: Match with active tracks ===
        matches, unmatched_dets, unmatched_tracks = self._match(
            detections, features, qualities
        )

        # Update matched tracks
        for track_idx, det_idx in matches:
            self.tracks[track_idx].update(
                bboxes[det_idx], features[det_idx], qualities[det_idx]
            )
            self.tracks[track_idx].last_seen_frame = self.frame_count

            # Update long-term memory with this identity
            if qualities[det_idx] > 0.4:
                self.long_term_memory.add_identity(
                    self.tracks[track_idx].track_id,
                    features[det_idx],
                    self.frame_count,
                    qualities[det_idx]
                )

        # === STAGE 2: Match with lost tracks (short-term buffer) ===
        if len(unmatched_dets) > 0 and len(self.lost_tracks) > 0:
            reid_matches = self._reid_match(
                unmatched_dets, bboxes, features, qualities
            )

            for lost_idx, det_idx in reid_matches:
                # Recover lost track
                recovered_track = self.lost_tracks.pop(lost_idx)
                recovered_track.update(
                    bboxes[det_idx], features[det_idx], qualities[det_idx]
                )
                recovered_track.state = 'confirmed'
                recovered_track.time_since_update = 0
                self.tracks.append(recovered_track)

                # Update statistics
                self.stats['reid_buffer_recoveries'] += 1

                # Update memory
                if qualities[det_idx] > 0.4:
                    self.long_term_memory.add_identity(
                        recovered_track.track_id,
                        features[det_idx],
                        self.frame_count,
                        qualities[det_idx]
                    )

                # Remove from unmatched
                unmatched_dets = [d for d in unmatched_dets if d != det_idx]

        # === STAGE 3: Match with long-term memory ===
        still_unmatched = []

        for det_idx in unmatched_dets:
            # Only search memory for high-quality detections
            if qualities[det_idx] < 0.3:
                still_unmatched.append(det_idx)
                continue

            # Search long-term memory
            matched_id = self.long_term_memory.search_memory(
                features[det_idx],
                self.frame_count
            )

            if matched_id is not None:
                # Create new track with recovered ID
                new_track = MemoryAwareTrack(
                    bboxes[det_idx],
                    features[det_idx],
                    track_id=matched_id,  # Use old ID!
                    quality=qualities[det_idx],
                    from_memory=True
                )
                new_track.last_seen_frame = self.frame_count
                new_track.state = 'confirmed'  # Immediately confirm
                new_track.memory_confirmed = True
                self.tracks.append(new_track)

                # Update statistics
                self.stats['memory_recoveries'] += 1

                # Update memory
                self.long_term_memory.add_identity(
                    matched_id,
                    features[det_idx],
                    self.frame_count,
                    qualities[det_idx]
                )
            else:
                # No match in memory either
                still_unmatched.append(det_idx)

        # Mark unmatched tracks as missed
        for track_idx in unmatched_tracks:
            self.tracks[track_idx].mark_missed()

        # === STAGE 4: Create NEW IDs only for unmatched detections ===
        for det_idx in still_unmatched:
            quality = qualities[det_idx] if det_idx < len(qualities) else 0.5

            # Only create track if quality is reasonable
            if quality > 0.3:
                # This is truly a new person - create new ID
                new_track = MemoryAwareTrack(
                    bboxes[det_idx],
                    features[det_idx],
                    quality=quality,
                    from_memory=False
                )
                new_track.last_seen_frame = self.frame_count
                self.tracks.append(new_track)

                # Add to memory immediately
                self.long_term_memory.add_identity(
                    new_track.track_id,
                    features[det_idx],
                    self.frame_count,
                    quality
                )

                # Update statistics
                self.stats['new_ids_created'] += 1
                print(f"  ✨ Created NEW ID {new_track.track_id} (no match in memory)")

        # Manage track lifecycle
        self._manage_tracks()

        # Periodic memory cleanup
        if self.frame_count % 100 == 0:
            self.long_term_memory.cleanup_memory(self.frame_count)

        # Return confirmed tracks
        outputs = []
        for track in self.tracks:
            if track.state == 'confirmed' and track.get_confidence() > 0.3:
                bbox = track.get_state()
                outputs.append([*bbox, track.track_id])

        return np.array(outputs) if outputs else np.empty((0, 5))

    def _manage_tracks(self):
        """Enhanced track management with memory storage"""
        active_tracks = []

        for track in self.tracks:
            if track.state == 'deleted':
                # Store in memory before deletion
                memory_feature = track.get_memory_feature() if hasattr(track, 'get_memory_feature') else track.get_feature()
                self.long_term_memory.add_identity(
                    track.track_id,
                    memory_feature,
                    self.frame_count,
                    quality=0.8  # Assume deleted tracks had reasonable quality
                )

                # Move to lost tracks buffer if it was a good track
                if (track.total_detections > 5 and
                    track.get_confidence() > 0.4 and
                    len(self.lost_tracks) < self.reid_buffer_size):
                    self.lost_tracks.append(track)
            else:
                active_tracks.append(track)

        self.tracks = active_tracks

        # Clean old lost tracks
        current_frame = self.frame_count
        self.lost_tracks = [
            t for t in self.lost_tracks
            if (current_frame - t.last_seen_frame) < 60
        ]

    def get_statistics(self):
        """Get tracking statistics"""
        return {
            **self.stats,
            'memory_summary': self.long_term_memory.get_memory_summary(),
            'active_tracks': len(self.tracks),
            'lost_buffer': len(self.lost_tracks),
            'memory_identities': len(self.long_term_memory.memory)
        }

# ============================================================================
# CELL 7: Visualization Helper Functions
# ============================================================================

def create_color_palette(n=100):
    """Generate distinct colors for different track IDs."""
    np.random.seed(42)
    palette = []
    for i in range(n):
        hue = (i * 0.618033988749895) % 1.0  # Golden ratio conjugate
        rgb = tuple(int(x * 255) for x in plt.cm.hsv(hue)[:3])
        palette.append(rgb)
    return palette


COLORS = create_color_palette(100)


def draw_tracks(frame, tracks, show_trajectory=True):
    """
    Draw bounding boxes, IDs, and trajectories on frame.
    Args:
        frame: image array
        tracks: Nx5 array [x1, y1, x2, y2, track_id]
        show_trajectory: whether to draw trajectory trails
    """
    result = frame.copy()

    for track in tracks:
        x1, y1, x2, y2, track_id = track
        x1, y1, x2, y2 = map(int, [x1, y1, x2, y2])
        track_id = int(track_id)

        # Get color for this track ID
        color = COLORS[track_id % len(COLORS)]

        # Draw bounding box
        cv2.rectangle(result, (x1, y1), (x2, y2), color, 2)

        # Draw ID label
        label = f"ID: {track_id}"
        label_size, _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        label_y1 = max(y1, label_size[1] + 10)
        cv2.rectangle(result, (x1, label_y1 - label_size[1] - 10),
                     (x1 + label_size[0], label_y1), color, -1)
        cv2.putText(result, label, (x1, label_y1 - 5),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

    return result


def draw_trajectories(frame, tracker, max_points=30):
    """Draw trajectory trails for all active tracks."""
    result = frame.copy()

    for track in tracker.tracks:
        if track.state == 'confirmed' and len(track.trajectory) > 1:
            color = COLORS[track.track_id % len(COLORS)]
            points = list(track.trajectory)

            # Draw lines between consecutive points
            for i in range(len(points) - 1):
                pt1 = tuple(map(int, points[i]))
                pt2 = tuple(map(int, points[i + 1]))
                thickness = max(1, int(2 * (i + 1) / len(points)))
                cv2.line(result, pt1, pt2, color, thickness)

            # Draw circle at current position
            if len(points) > 0:
                pt = tuple(map(int, points[-1]))
                cv2.circle(result, pt, 4, color, -1)

    return result

# ============================================================================
# CELL 9: Main Execution with Memory-Enhanced Tracker
# ============================================================================

def run_tracker_on_mot17(seq_path=None, output_video='mot17_tracked.mp4',
                         max_frames=None, start_frame=0,
                         model_path='best_model.pth'):
    """Run memory-enhanced BoT-SORT tracker"""

    print("=" * 80)
    print("Initializing MEMORY-ENHANCED BoT-SORT Tracker")
    print("=" * 80)

    if not os.path.exists(model_path):
        print(f"\n❌ ERROR: Model file not found: {model_path}")
        return

    if seq_path is None:
        seq_path = select_mot17_sequence()

    frame_paths = load_mot17_sequence(seq_path)

    if start_frame > 0:
        frame_paths = frame_paths[start_frame:]
    if max_frames:
        frame_paths = frame_paths[:max_frames]

    # Initialize detector
    print("\nLoading YOLOv11 detector...")
    detector = YOLO('yolo11n.pt')
    print("✓ Detector loaded")

    # Initialize enhanced feature extractor
    print(f"\nLoading enhanced feature extractor from {model_path}...")
    feature_extractor = EnhancedFeatureExtractor(
        model_path=model_path,
        device=device,
        buffer_size=100,
        min_feature_quality=0.2
    )
    print("✓ Enhanced feature extractor loaded")

    # Initialize MEMORY-ENHANCED tracker
    print("Initializing memory-enhanced BoT-SORT tracker...")
    tracker = MemoryEnhancedBoTSORT(
        feature_extractor=feature_extractor,
        max_age=120,
        min_hits=5,
        iou_threshold=0.3,
        lambda_iou=0.2,
        lambda_reid=0.8,
        reid_threshold=0.70,      # Lost buffer threshold
        reid_buffer_size=100,
        memory_threshold=0.65,    # Long-term memory threshold (higher = more strict)
        memory_size=200           # Max identities to remember
    )
    print("✓ Memory-enhanced tracker initialized")
    print("  - 🧠 Long-term memory enabled (200 identities)")
    print("  - 📦 Short-term buffer enabled (50 tracks)")
    print("  - 🔍 Multi-scale feature extraction enabled")
    print("  - ⚖️ Quality-aware matching enabled")

    # Prepare video writer
    first_frame = cv2.imread(frame_paths[0])
    h, w = first_frame.shape[:2]
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_video, fourcc, 20.0, (w, h))

    print("\n" + "=" * 80)
    print("Processing frames...")
    print("=" * 80)

    total_detections = 0

    for idx, frame_path in enumerate(frame_paths):
        frame = cv2.imread(frame_path)
        if frame is None:
            continue

        # Detect objects
        results = detector(frame, verbose=False)[0]
        detections = []

        for box in results.boxes:
            if box.cls[0] == 0:  # person
                x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
                conf = box.conf[0].cpu().numpy()
                if conf > 0.5:
                    detections.append([x1, y1, x2, y2, conf])

        detections = np.array(detections) if detections else np.empty((0, 5))
        total_detections += len(detections)

        # Update tracker
        tracks = tracker.update(frame, detections)

        # Get statistics
        stats = tracker.get_statistics()

        # Visualize
        vis_frame = draw_tracks(frame, tracks, show_trajectory=False)
        vis_frame = draw_trajectories(vis_frame, tracker)

        # Add comprehensive info
        seq_name = os.path.basename(seq_path)

        # Line 1: Frame info
        info_text1 = f"{seq_name} | Frame: {idx+1}/{len(frame_paths)} | Active: {len(tracks)}"
        cv2.putText(vis_frame, info_text1, (10, 25),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        # Line 2: Memory stats
        info_text2 = f"Memory: {stats['memory_identities']} IDs | Buffer: {len(tracker.lost_tracks)} | Det: {len(detections)}"
        cv2.putText(vis_frame, info_text2, (10, 50),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 255), 2)

        # Line 3: Recovery stats
        info_text3 = f"Recoveries - Memory: {stats['memory_recoveries']} | Buffer: {stats['reid_buffer_recoveries']} | New IDs: {stats['new_ids_created']}"
        cv2.putText(vis_frame, info_text3, (10, 75),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 200, 0), 2)

        out.write(vis_frame)

        if (idx + 1) % 10 == 0:
            print(f"  [{idx+1}/{len(frame_paths)}] {stats['memory_summary']} | "
                  f"Memory recoveries: {stats['memory_recoveries']} | "
                  f"Buffer recoveries: {stats['reid_buffer_recoveries']} | "
                  f"New IDs: {stats['new_ids_created']}")

    out.release()

    stats = tracker.get_statistics()

    print("\n" + "=" * 80)
    print("TRACKING COMPLETE!")
    print("=" * 80)
    print(f"✓ Total frames processed: {len(frame_paths)}")
    print(f"✓ Total detections: {total_detections}")
    print(f"✓ Total unique IDs created: {Track._count}")
    print(f"\n📊 RECOVERY STATISTICS:")
    print(f"  - Memory recoveries: {stats['memory_recoveries']}")
    print(f"  - Buffer recoveries: {stats['reid_buffer_recoveries']}")
    print(f"  - New IDs created: {stats['new_ids_created']}")
    print(f"\n🧠 MEMORY STATE:")
    print(f"  - {stats['memory_summary']}")
    print(f"  - Final active tracks: {stats['active_tracks']}")
    print(f"  - Lost track buffer: {stats['lost_buffer']}")
    print("=" * 80)

    return output_video

# ============================================================================
# CELL 10: Custom Video Tracking with Memory
# ============================================================================

def track_custom_video(video_path, output_path='output_tracked.mp4',
                       conf_threshold=0.5, max_frames=None,
                       model_path='/content/best_model.pth'):
    """Run memory-enhanced BoT-SORT on custom video"""

    print("=" * 80)
    print(f"Running MEMORY-ENHANCED Tracker on: {video_path}")
    print(f"Using model: {model_path}")
    print("=" * 80)

    if not os.path.exists(video_path):
        print(f"Error: Video not found: {video_path}")
        return

    if not os.path.exists(model_path):
        print(f"Error: Model not found: {model_path}")
        return

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("Error: Cannot open video")
        return

    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if max_frames:
        total_frames = min(total_frames, max_frames)

    print(f"Video: {width}x{height} @ {fps} FPS, {total_frames} frames")

    # Initialize components
    print("\nLoading detector...")
    detector = YOLO('yolo11s.pt')
    print("✓ Detector loaded")

    print(f"Loading feature extractor...")
    feature_extractor = EnhancedFeatureExtractor(
        model_path=model_path,
        device=device,
        buffer_size=500,
        min_feature_quality=0.05
    )
    print("✓ Feature extractor loaded")

    print("Initializing memory-enhanced tracker...")
    tracker = MemoryEnhancedBoTSORT(
        feature_extractor=feature_extractor,
        max_age=600,
        min_hits=5,
        iou_threshold=0.4,
        lambda_iou=0.9,
        lambda_reid=0.1,
        reid_threshold=0.30,
        reid_buffer_size=50,
        memory_threshold=0.45,
        memory_size=200
    )
    print("✓ Tracker initialized with long-term memory")

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

    print("\n" + "=" * 80)
    print("Processing video...")
    print("=" * 80)

    frame_idx = 0

    while True:
        ret, frame = cap.read()
        if not ret or (max_frames and frame_idx >= max_frames):
            break

        # Detect
        results = detector(frame, verbose=False)[0]
        detections = []

        for box in results.boxes:
            if box.cls[0] == 0:  # person
                x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
                conf = box.conf[0].cpu().numpy()
                if conf > conf_threshold:
                    detections.append([x1, y1, x2, y2, conf])

        detections = np.array(detections) if detections else np.empty((0, 5))

        # Track
        tracks = tracker.update(frame, detections)
        stats = tracker.get_statistics()

        # Visualize
        vis_frame = draw_tracks(frame, tracks, show_trajectory=False)
        vis_frame = draw_trajectories(vis_frame, tracker)

        # Add info
        info1 = f"Frame: {frame_idx+1}/{total_frames} | Active: {len(tracks)} | Memory: {stats['memory_identities']} IDs"
        cv2.putText(vis_frame, info1, (10, 25),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

        info2 = f"Recoveries: {stats['memory_recoveries']} | New IDs: {stats['new_ids_created']}"
        cv2.putText(vis_frame, info2, (10, 50),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 255), 2)

        out.write(vis_frame)

        if (frame_idx + 1) % 30 == 0:
            print(f"  [{frame_idx+1}/{total_frames}] Active: {len(tracks)} | "
                  f"Memory: {stats['memory_identities']} | "
                  f"Recoveries: {stats['memory_recoveries']}")

        frame_idx += 1

    cap.release()
    out.release()

    stats = tracker.get_statistics()

    print("\n" + "=" * 80)
    print("✓ Tracking complete!")
    print(f"✓ Output: {output_path}")
    print(f"✓ Frames: {frame_idx}")
    print(f"✓ Total IDs: {Track._count}")
    print(f"✓ Memory recoveries: {stats['memory_recoveries']}")
    print(f"✓ New IDs created: {stats['new_ids_created']}")
    print("=" * 80)


# ============================================================================
# USAGE EXAMPLES
# ============================================================================

def reset_tracker_state():
    """
    Resets the global track ID counter to 0.
    Call this before processing a new video if you want IDs to start from 0.
    """
    # Reset the static counter in the base Track class
    Track._count = 0
    print("✓ Track ID counter has been reset to 0.")


if __name__ == '__main__':
    # Example 1: Run on custom video with custom model
    track_custom_video(
        video_path='/content/Caregiver_gives_medicine_to_patient_233c3e973c.mp4',
        output_path='output_tracked_custom.mp4',
        conf_threshold=0.5,
        max_frames=None,  # Process all frames
        model_path='/content/best_model.pth'  # Your pretrained model
    )

    reset_tracker_state()

